
import image1 from "./images/image1.jpg"
import image2 from "./images/image2.jpg"
import image3 from "./images/image3.jpg"
import image4 from "./images/image4.jpg"
import image5 from "./images/image5.jpg"

const historyData = [
    {
        heading:"THE MET",
        content:`The Metropolitan Museum of Art's earliest roots date back to 1866 in Paris, France, when a group of Americans agreed to create a "national institution and gallery of art" to bring art and art education to the American people. The lawyer John Jay, who proposed the idea, swiftly moved forward with the project upon his return to the United States from France. Under Jay's presidency, the Union League Club in New York rallied civic leaders, businessmen, artists, art collectors, and philanthropists to the cause. On April 13, 1870, The Metropolitan Museum of Art was incorporated, opening to the public in the Dodworth Building at 681 Fifth Avenue. On November 20 of that same year, the Museum acquired its first object, a Roman sarcophagus. In 1871, 174 European paintings, including works by Anthony van Dyck, Nicolas Poussin, and Giovanni Battista Tiepolo, entered the collection.
        On March 30, 1880, after a brief move to the Douglas Mansion at 128 West 14th Street, the Museum opened to the public at its current site on Fifth Avenue and 82nd Street. The architects Calvert Vaux and Jacob Wrey Mould designed the initial Ruskinian Gothic structure, the west facade of which is still visible in the Robert Lehman Wing. The building has since expanded greatly, and the various additions—built as early as 1888—now completely surround the original structure.
        The Museum's collection continued to grow throughout the rest of the 19th century. The 1874–76 purchase of the Cesnola Collection of Cypriot art—works dating from the Bronze Age to the end of the Roman period—helped to establish The Met's reputation as a major repository of classical antiquities. When the American painter John Kensett died in 1872, 38 of his canvases came to the Museum, and in 1889, the Museum acquired two works by Édouard Manet.
        The Museum's Beaux-Arts Fifth Avenue facade and Great Hall, designed by the architect and founding Museum Trustee Richard Morris Hunt, opened to the public in December 1902. The Evening Post reported that at last New York had a neoclassical palace of art, "one of the finest in the world, and the only public building in recent years which approaches in dignity and grandeur the museums of the old world."
        By the 20th century, the Museum had become one of the world's great art centers. In 1907, the Museum acquired a work by Auguste Renoir, and in 1910, The Met was the first public institution in the world to acquire a work of art by Henri Matisse. The ancient Egyptian hippopotamus statuette that is now the Museum's unofficial mascot, "William," entered the collection in 1917. Today, virtually all of the Museum's 26,000 ancient Egyptian objects, the largest collection of Egyptian art outside of Cairo, are on display. By 1979, the Museum owned five of the fewer than 35 known paintings by Johannes Vermeer, and now The Met's 2,500 European paintings comprise one of the greatest such collections in the world. The American Wing now houses the world's most comprehensive collection of American paintings, sculpture, and decorative arts. Other major collections belonging to the Museum include arms and armor, the arts of Africa, Oceania, and the Americas, ancient Near Eastern art, Asian art, costume, drawings and prints, European sculpture and decorative arts, Greek and Roman art, Islamic art, medieval art, modern and contemporary art, musical instruments, photographs, and the Robert Lehman Collection.
        Today, tens of thousands of objects are on view at any given time in the Museum's two-million-square-foot building. A comprehensive architectural plan for the Museum by the architects Kevin Roche John Dinkeloo and Associates was approved in 1971 and completed in 1991. Among the additions to the Museum as part of the master plan are the Robert Lehman Wing (1975), which houses an extraordinary collection of Old Masters, as well as Impressionist and Post-Impressionist art; The Sackler Wing (1978), which houses the Temple of Dendur; The American Wing (1980), whose diverse collection includes 25 recently renovated period rooms; The Michael C. Rockefeller Wing (1982) displaying the arts of Africa, Oceania, and the Americas; the Lila Acheson Wallace Wing (1987) of modern and contemporary art; and the Henry R. Kravis Wing (1991) devoted to European sculpture and decorative arts from the Renaissance to the beginning of the 20th century.
        With the expansion of the building complete, The Met has continued to refine and reorganize its collection. In 1998, the Arts of Korea gallery opened to the public, completing a major suite of galleries devoted to the arts of Asia. The Ancient Near Eastern Art galleries reopened to the public in 1999 following a renovation. In 2007, several major projects at the south end of the building were completed, most notably the 15-year renovation and reinstallation of the entire suite of Greek and Roman Art galleries. Galleries for Oceanic and Native North American Art also opened in 2007, as well as the new Galleries for Nineteenth- and Early Twentieth-Century Paintings and Sculpture and the Ruth and Harold D. Uris Center for Education.        
        On November 1, 2011, the Museum's New Galleries for the Art of the Arab Lands, Turkey, Iran, Central Asia, and Later South Asia opened to the public. On the north side of the Museum, The Met's New American Wing Galleries for Paintings, Sculpture, and Decorative Arts reopened on January 16, 2012, signaling the completion of the third and final phase of The American Wing's renovation.
        In May 2021, The Met installed a plaque on the Fifth Avenue facade recognizing Lenapehoking, the homeland of the Indigenous Lenape peoples.`,
        image:[image1,image2],
    },
    {
        heading:"THE MET CLOISTERS",
        content:`The Met Cloisters, which opened to the public in 1938, is the branch of The Metropolitan Museum of Art devoted to the art and architecture of medieval Europe. Located in Fort Tryon Park in northern Manhattan, on a spectacular four-acre lot overlooking the Hudson River, the modern museum building is not a copy of any specific medieval structure but is rather an ensemble informed by a selection of historical precedents, with a deliberate combination of ecclesiastical and secular spaces arranged in chronological order. Elements from medieval cloisters—Saint-Michel-de-Cuxa, Saint-Guilhem-le-Désert, Trie-sur-Baïse, Froville, and elements once thought to have come from Bonnefont-en-Comminges—and from other sites in Europe have been incorporated into the fabric of the building.
        Three of the reconstructed cloisters feature gardens planted according to horticultural information found in medieval treatises and poetry, garden documents and herbals, and medieval works of art such as tapestries, stained-glass windows, and column capitals. Approximately 2,000 works of art from medieval Europe, largely dating from the 12th through the 15th century and including exquisite illuminated manuscripts, stained glass, metalwork, enamels, ivories, and tapestries, are exhibited in this unique context.
        Much of the sculpture at The Met Cloisters was acquired by George Grey Barnard (1863–1938), a prominent American sculptor, and an avid collector and dealer of medieval art. Barnard opened his original Cloisters on Fort Washington Avenue to the public in 1914. Through the generosity of John D. Rockefeller, Jr. (1874–1960), the Museum acquired Barnard's Cloisters and most of its contents in 1925. Early on, it was clear that a new, larger building would be needed to display the collection in a more scholarly fashion. Rockefeller donated to New York City, and financed the conversion of, some 56 acres of land just north of Barnard's museum, which became Fort Tryon Park—approximately four acres of which was destined as the site for the new museum. Following J. Pierpont Morgan's purchase of 12 miles of the New Jersey Palisades in 1901 to preserve the cliffs and shoreline from excessive quarrying, Rockefeller in 1933 donated some 700 additional acres of the Palisades' plateau to preserve the view from The Met Cloisters. In addition to providing the grounds and building to house the Barnard collection, Rockefeller contributed works of art from his own collection—including the celebrated Unicorn Tapestries—and established an endowment for operations and future acquisitions.
        The new Cloisters museum building was designed by Charles Collens (1873–1956) who, together with Henry C. Pelton, designed the Riverside Church in New York City. Joseph Breck (1885–1933), a curator of decorative arts and assistant director of The Metropolitan Museum of Art, and James J. Rorimer (1905–1966), who would later be named the Museum's director, were primarily responsible for overseeing the building's design and construction. Balancing Collens's interpretation with strict attention to historical accuracy, Breck and Rorimer created in the galleries a clear and logical flow from the Romanesque (ca. 1000–ca. 1150) through the Gothic period (ca. 1150–1520).
        The Cloisters opened to the public on May 10, 1938. In 1958, the 12th-century limestone apse from the church in Fuentidueña, Spain, arrived to become part of the structure. The Treasury, which contains objects created for liturgical celebrations, personal devotions, and secular uses, was renovated in 1988. Major improvement to the infrastructure, climatization, and gallery spaces has continued to this day, including a new skylight in the cloister from Saint-Guilhem-le-Désert, a new objects conservation lab, the preservation of limestone windows in the Early Gothic and Late Gothic Halls, and many others.
        The collection at The Met Cloisters continues to grow, thanks to Rockefeller's endowment and other significant gifts. Among its masterpieces are an early 15th-century French illuminated book of hours, The Belles Heures of Jean de France, Duc de Berry; a richly carved, 12th-century ivory cross attributed by some to the English abbey of Bury Saint Edmunds; stained-glass windows from the castle chapel at Ebreichsdorf, Austria; a stone Virgin of the mid-13th century from the choir screen of Strasbourg Cathedral in France; and the Merode Triptych, representing the Annunciation, by the workshop of the 15th-century Netherlandish master Robert Campin.`,
        image:[image5]
    },
    {
        heading:"HISTORY OF THE BUILDING",
        content:`When the great Bauhaus architect Marcel Breuer (1902–1981) received the prestigious commission to build a new museum of American art in New York in 1963, it was the beginning of one of the defining decades of the century. All over Manhattan, dizzying monuments to consumerism, television, and commerce were constructed in glass and steel.
        Acclaimed for his mastery of stone and concrete with institutional buildings and private homes across Europe, the Hungarian-born émigré crafted the Whitney Museum of American Art, a living monument in contrast with the transient, disposable trends of its time, at the peak of his career (it was constructed in 1963–66). Convinced that the sandy, genteel apartment buildings of the Upper East Side would soon be replaced with a new skyline of gleaming office towers, and equally convinced of the importance of longevity in architecture, Breuer conceived the museum as a solid, permanent sanctuary for the art within and all that it represented.
        In this contained, self-confident building on Madison Avenue at the corner of 75th Street, Breuer created a personal and intimate museum experience. Described by the New York Times in 1966 as "harsh, but handsome," its crisp granite facade—sometimes dark gray, often pinkish—steps up and forward over the entrance, peppered with distinctive asymmetrical windows that reveal almost nothing of the interior activity. The street level, on the other hand, is wide open, Breuer's way of helping the visitor transition from the hustle of Madison Avenue to a profound engagement with art. The entrance experience is a slow procession that begins with a walk under a low concrete canopy and over a sunken garden, which reveals great glass walls into the lower ground spaces, before entering the grand, iconic lobby with its rows upon rows of moonlike shades. Only then could visitors move either down toward the sculpture court or upward and into the galleries. The Whitney Museum’s desire for a flexible exhibition space led to the large, open gallery spaces that now remain. Three of its floors suspend precast concrete, open-grid ceilings designed to allow movable wall panels, and flexible lighting that can be rearranged for each new exhibition.
        As Breuer was famously the youngest furniture master at the Bauhaus in Dessau, where he invented tubular-steel furniture at the age of 24, there are numerous fine details and materials found throughout this building. The handcrafted staircases and the burnished bronze finishes throughout speak to the level of sophistication, artistry, care, and commitment that Breuer had in creating the building. Breuer himself worked on the roughly textured concrete on the inside of the lobby.
        The Breuer building has proved its status as a singular museum experience unlike any other, and remains one of the most recognizable modern icons in New York and one of the world's landmark arts buildings. It is in honor of the influential architect who designed it that The Metropolitan Museum of Art has named the building The Met Breuer.`,
        image:[image3,image4],
    }
]

export default historyData;