import greathall from './images/innerImages/GreatHall.jpg'
import RomanArt from './images/innerImages/GreekAndRoman.jpg'
import ArmericanWing from './images/innerImages/AmericanWing.jpg'
import Arms from './images/innerImages/Arms.jpg'
import ContemporaryArt from './images/innerImages/ContemporaryArt.jpg'
import DecrativeArts from './images/innerImages/DecorativeArts.jpg'
import EgyptianArt from './images/innerImages/EgyptianArt.jpg'
import Lehman from './images/innerImages/LehmanCollection.jpg'
import MedArt from './images/innerImages/MedievalArt.jpg'
import RockWing from './images/innerImages/RockefellerWing.jpg'

export const places = [
    {0: ['The Great Hall',"The Great Hall has been the majestic main entry of The Metropolitan Museum of Art for more than a century. When it opened to the public in December 1902, the Evening Postnewspaper reported that at last New York had a neoclassical palace of art, \"one of the finest in the world, and the only public building in recent years which approaches in dignity and grandeur the museums of the old world.\" Architect Richard Morris Hunt, who was one of the founding trustees of the Metropolitan and the most fashionable architect of his day, designed both the Museum's classical Beaux-Arts Fifth Avenue fa√ßade and the Great Hall, which now greets more than five million visitors each year. Hunt did not live to see the project completed‚Äîafter his death in 1895, his son Richard Howland Hunt carried out the final stages of work.",greathall]},
    {1: ['Greek and Roman Art','The Museum\'s collection of Greek and Roman art comprises more than 17,000 works ranging in date from the Neolithic period (ca. 4500 B.C.) to the time of the Roman emperor Constantine\'s conversion to Christianity in A.D. 312. It includes the art of many cultures and is among the most comprehensive in North America. The geographic regions represented are Greece and Italy, but not as delimited by modern political frontiers: much of Asia Minor on the periphery of Greece was settled by Greeks; Cyprus became increasingly Hellenized in the course of its long history; and Greek colonies were established around the Mediterranean basin and on the shores of the Black Sea. For Roman art, the geographical limits coincide with the expansion of the Roman Empire. The department also exhibits the pre-Greek art of Greece and the pre-Roman art of Italy, notably of the Etruscans.',RomanArt]},
    {2: ['The Michael C. Rockefeller Wing',"The Met collection of art of the peoples of sub-Saharan Africa, the Pacific Islands, and North, Central, and South America comprises more than 11,000 works of art of varied materials and types, representing diverse cultural traditions from as early as 3000 B.C.E. to the present. Highlights include decorative and ceremonial objects from the Court of Benin in Nigeria; sculpture from West and Central Africa; images of gods, ancestors, and spirits from New Guinea, Island Melanesia, Polynesia, and Island Southeast Asia; and objects of gold, ceramic, and stone from the Precolumbian cultures of Mexico and Central and South America.",RockWing]},
    {3: ['Modern and Contemporary Art',"Use our Audio Guide in the galleries to learn more about the collection.The Modern and Contemporary Art department is devoted to the study, collection and exhibition of art from 1890 to the present. An era marked by seismic cultural, social and political shifts across the globe, artistic responses to these changes have shaped multiple modernities and diverse contemporary practices. The department seeks to research and present the interconnected and richly variegated narratives and experiences that inform the art of this period from around the world. Historically focused on the art of Western Europe and North America, since 2012. the department has greatly expanded and diversified its collection of modern and contemporary art, especially through works by women and artists of color, with particular emphasis on acquisitions from Latin America, South Asia, the Middle East, North Africa and Turkey. Today, its collections span a range of media, including paintings, sculpture, works on paper, design, decorative arts, and time-based media. The department presents rotating selections from its dynamic holdings in the Modern and Contemporary galleries of the Lila Acheson Wallace Wing.",ContemporaryArt]},
    {4: ['European Sculpture and Decorative Arts',"The 50,000 objects in the Museum's comprehensive and historically important collection of European sculpture and decorative arts reflect the development of a number of art forms in Western European countries from the early 15th through the early 20th century. The holdings include sculpture in many sizes and media, woodwork and furniture, ceramics and glass, metalwork and jewelry, horological and mathematical instruments, and tapestries and textiles. Ceramics made in Asia for export to European markets and sculpture and decorative arts produced in Latin America during this period are also included among these works.",DecrativeArts]},
    {5: ['The Robert Lehman Collection',"The Robert Lehman Collection is one of the most distinguished privately assembled art collections in the United States. Robert Lehman's bequest to The Met, a collection of extraordinary quality and breadth acquired over the course of 60 years, is a remarkable example of 20th-century American collecting. Spanning 700 years of western European art, from the 14th to the 20th centuries, the 2,600 works include paintings, drawings, manuscript illumination, sculpture, glass, textiles, antique frames, maiolica, enamels, and precious jeweled objects.",Lehman]},
    {6: ['Medieval Art and The Cloisters',"The Museum's collection of medieval and Byzantine art is among the most comprehensive in the world. Displayed in both The Met Fifth Avenue and in the Museum's branch in northern Manhattan, The Met Cloisters, the collection encompasses the art of the Mediterranean and Europe from the fall of Rome in the 4th century to the beginning of the Renaissance in the early 16th century. It also includes pre-medieval European works of art created during the Bronze Age and early Iron Age.",MedArt]},
    {7: ['Egyptian Art',"The Met collection of ancient Egyptian art consists of approximately 26,000 objects of artistic, historical, and cultural importance, dating from the Paleolithic to the Roman period (ca. 300,000 B.C.–A.D. 4th century). More than half of the collection is derived from the Museum's 35 years of archaeological work in Egypt, initiated in 1906 in response to increasing Western interest in the culture of ancient Egypt.",EgyptianArt]},
    {8: ['The American Wing',"Ever since its establishment in 1870 the Museum has acquired important examples of American Art. A separate \"American Wing\" building to display the domestic arts of the 17th early 19th centuries opened in 1924; paintings galleries and an enclosed sculpture court were added in 1980.",ArmericanWing]},
    {9: ['Arms and Armor',"Arms and armor have been a vital part of virtually all cultures for thousands of years, pivotal not only in conquest and defense, but also in court pageantry and ceremonial events. Throughout time the best armor and weapons have represented the highest artistic and technical capabilities of the society and period in which they were made, forming a unique aspect of both art history and material culture.",Arms]},
    {10: ['European Sculpture and Decorative Arts',"The 50,000 objects in the Museum's comprehensive and historically important collection of European sculpture and decorative arts reflect the development of a number of art forms in Western European countries from the early 15th through the early 20th century. The holdings include sculpture in many sizes and media, woodwork and furniture, ceramics and glass, metalwork and jewelry, horological and mathematical instruments, and tapestries and textiles. Ceramics made in Asia for export to European markets and sculpture and decorative arts produced in Latin America during this period are also included among these works.",DecrativeArts]},
    {11: ['Medieval Art and The Cloisters',"The Museum's collection of medieval and Byzantine art is among the most comprehensive in the world. Displayed in both The Met Fifth Avenue and in the Museum's branch in northern Manhattan, The Met Cloisters, the collection encompasses the art of the Mediterranean and Europe from the fall of Rome in the 4th century to the beginning of the Renaissance in the early 16th century. It also includes pre-medieval European works of art created during the Bronze Age and early Iron Age.",MedArt]},
    {12: ['The Michael C. Rockefeller Wing',"The Met collection of art of the peoples of sub-Saharan Africa, the Pacific Islands, and North, Central, and South America comprises more than 11,000 works of art of varied materials and types, representing diverse cultural traditions from as early as 3000 B.C.E. to the present. Highlights include decorative and ceremonial objects from the Court of Benin in Nigeria; sculpture from West and Central Africa; images of gods, ancestors, and spirits from New Guinea, Island Melanesia, Polynesia, and Island Southeast Asia; and objects of gold, ceramic, and stone from the Precolumbian cultures of Mexico and Central and South America.",RockWing]}
]